

development:
  adapter: mysql2
  encoding: utf8
  database: task_manager
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: task_manager
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: task_manager
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
